git config --global alias.a "add" 
git config --global alias.b "branch"
git config --global alias.c "checkout"
git config --global alias.ch "cherry-pick"
git config --global alias.d "diff"
git config --global alias.l "log --graph --all --format='%%x09%%C(cyan bold)%%an%%Creset%%x09%%C(yellow)%%h%%Creset %%C(green reverse)%%d%%Creset%%s' --branches"
git config --global alias.rmh "reset --mixed head"
git config --global alias.rhh "reset --hard head"
git config --global alias.s "status"
